import gamestate
import player

game = gamestate.GameState('303234', (0.02, 0.05))
game.new_hand([player.Player(100, pos) for pos in ['sb', 'bb', 'lj', 'hj', 'co', 'btn']], 4)
game.print_gamestate()
game.bet(3.0)
game.next_player()
game.fold()
game.next_player()
game.bet(6.0)
game.next_player()
game.fold()
game.next_player()
game.fold()
game.next_player()
game.fold()
game.next_player()
game.bet(9.0)
game.next_player()
game.bet(12.0)
game.next_player()
game.bet(15.0)
print(game.facing_action())